services:
  lineage-build:
    image: lineageos4microg/docker-lineage-cicd
    volumes:
      - "./build/lineage:/srv/src"
      - "./build/zips:/srv/zips"
      - "./build/logs:/srv/logs"
      - "./build/cache:/srv/cache"
      - "./local_manifests:/srv/local_manifests"
      - "./scripts:/srv/userscripts"
    environment:
      - "BRANCH_NAME=lineage-18.1"
      - "DEVICE_LIST=redfin"
      - "SIGN_BUILDS=true"
      - "USER_BUILD_SPOOFING=yes"
      - "BUILD_TYPE=user"
      - "INCLUDE_PROPRIETARY=false"
      - "REPO_INIT_ARGS=--depth=1"